Use of deprecated frombytes when processing videos causes the task to fail
(Anonymous contribution, not by me)

  When transcoding a video using a recent version of PIL transcoding a
  video fails reproducible. The reason for this is an AttributeError:
  'module' object has no attribute 'frombytes'gets raised, while a
  thumbnails is being created. This is because frombytes alias was
  deprecated in favor of fromstring.